#!/bin/bash
#
# Google Music Manager Wrapper
# Copyright (C) 2017 James T. Lee
#
# The google-musicmanager process daemonizes itself which causes the Docker
# container to stop.  This wrapper waits for the daemon to stop, and takes care
# to pass a couple of exit signals to it.
#

echo "Starting VNC Server"
vncserver
echo "Starting Google MusicManager"
/usr/bin/google-musicmanager "$@"
while true do sleep 99; done
